//Location in EEPROM for each thing we want to store between power cycles
enum eepromLocations {
  LOCATION_I2C_ADDRESS, //Device's address
  LOCATION_RED_BRIGHTNESS,
  LOCATION_GREEN_BRIGHTNESS,
  LOCATION_BLUE_BRIGHTNESS,
  LOCATION_RED_CONNECT_AMOUNT,
  LOCATION_GREEN_CONNECT_AMOUNT = LOCATION_RED_CONNECT_AMOUNT + 2, //Previous was an int
  LOCATION_BLUE_CONNECT_AMOUNT = LOCATION_GREEN_CONNECT_AMOUNT + 2, //Previous was an int
  LOCATION_TURN_INTERRUPT_TIMEOUT_AMOUNT = LOCATION_BLUE_CONNECT_AMOUNT + 2, //Previous was an int
};

//Defaults for each setting
const byte I2C_ADDRESS_DEFAULT = 0x3F;
const byte I2C_FORCED_ADDRESS = 0x3E; //This is the address we go to incase user closes the address jumper

//Commands
enum encoderCommands {
  COMMAND_GET_VERSION = 0x00,
  COMMAND_GET_ENCODER_COUNT,
  COMMAND_SET_ENCODER_COUNT,
  COMMAND_GET_DIFFERENCE,
  COMMAND_GET_BUTTON_STATE, //Current state of button
  COMMAND_GET_LAST_ENCODER_EVENT, //Millis since last movement of knob
  COMMAND_GET_LAST_BUTTON_EVENT, //Millis since last press/release
  COMMAND_IS_CLICKED, //True if user has pressed and released button since last isClicked() command

  COMMAND_GET_RED,
  COMMAND_GET_GREEN,
  COMMAND_GET_BLUE,
  COMMAND_GET_COLOR, //Get all three colors
  COMMAND_SET_RED,
  COMMAND_SET_GREEN,
  COMMAND_SET_BLUE,
  COMMAND_SET_COLOR,

  COMMAND_GET_CONNECT_RED,
  COMMAND_GET_CONNECT_GREEN,
  COMMAND_GET_CONNECT_BLUE,
  COMMAND_GET_CONNECT_COLOR,
  COMMAND_SET_CONNECT_RED, //Amount to change red LED for each encoder tick
  COMMAND_SET_CONNECT_GREEN,
  COMMAND_SET_CONNECT_BLUE,
  COMMAND_SET_CONNECT_COLOR,

  COMMAND_GET_TURN_INT_TIMEOUT,
  COMMAND_SET_TURN_INT_TIMEOUT,
  COMMAND_CHANGE_ADDRESS = 0xC7,
};

//Responses to commands
enum encoderResponses {
  RESPONSE_GET_VERSION,
  RESPONSE_GET_ENCODER_COUNT,
  RESPONSE_GET_DIFFERENCE,
  RESPONSE_GET_BUTTON_STATE,

  RESPONSE_GET_LAST_ENCODER_EVENT,
  RESPONSE_GET_LAST_BUTTON_EVENT,

  RESPONSE_GET_RED,
  RESPONSE_GET_GREEN,
  RESPONSE_GET_BLUE,
  RESPONSE_GET_COLOR,

  RESPONSE_GET_CONNECT_RED,
  RESPONSE_GET_CONNECT_GREEN,
  RESPONSE_GET_CONNECT_BLUE,
  RESPONSE_GET_CONNECT_COLOR,

  RESPONSE_GET_TURN_INT_TIMEOUT,
  RESPONSE_IS_CLICKED,
};
